### ISSUE TITLE
Error With Step 2 of Registration.

### ISSUE THREAD

**Issue by arajesh17** [Auditory-Biophysics-Lab/Slicer-ABLTemporalBoneSegmentation#4]
Hello,

I am excited to try out this module. I love the method and the  work that the lab has done. I recently downloaded the slicer extension and am having an error on step2 of the rigid registration. I have copied the error message below:

"""
itkAdvancedImageToImageMetric.hxx
File: D:\D\S\S-1-E-b\SlicerElastix-build\elastix\Common\CostFunctions\itkAdvancedImageToImageMetric.hxx
Line: 969
Line: 969
Description: itk::ERROR: itk::ERROR: AdvancedMattesMutualInformationMetric(0000025C5EC9B2E0): Too many samples map outside moving image buffer: 0 / 1119
Description: itk::ERROR: itk::ERROR: AdvancedMattesMutualInformationMetric(0000025C5EC9B2E0): Too many samples map outside moving image buffer: 0 / 1119

Error occurred during actual registration.
Error occurred during actual registration.

Errors occurred!
Errors occurred!
Error: Command 'elastix' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:/Users/anand/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/ABLTemporalBoneSegmentation/lib/Slicer-4.11/qt-scripted-modules/ABLTemporalBoneSegmentationModule.py", line 635, in process_transform
    output = function()
  File "C:/Users/anand/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/ABLTemporalBoneSegmentation/lib/Slicer-4.11/qt-scripted-modules/ABLTemporalBoneSegmentationModule.py", line 812, in transform
    log_callback=self.update_rigid_progress)
  File "C:/Users/anand/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/ABLTemporalBoneSegmentation/lib/Slicer-4.11/qt-scripted-modules/ABLTemporalBoneSegmentationModule.py", line 1318, in apply_elastix_rigid_registration
    movingVolumeMaskNode=mask_node
  File "C:\Users\anand\AppData\Local\NA-MIC\Slicer 4.11.20210226\NA-MIC\Extensions-29738\SlicerElastix\lib\Slicer-4.11\qt-scripted-modules\Elastix.py", line 807, in registerVolumes
    self.logProcessOutput(ep)
  File "C:\Users\anand\AppData\Local\NA-MIC\Slicer 4.11.20210226\NA-MIC\Extensions-29738\SlicerElastix\lib\Slicer-4.11\qt-scripted-modules\Elastix.py", line 728, in logProcessOutput

------------------------------
Reloading module: ABLTemporalBoneSegmentationModule
------------------------------

    raise subprocess.CalledProcessError(return_code, "elastix")
subprocess.CalledProcessError: Command 'elastix' returned non-zero exit status 1.
"""

I have placed 3 of the anatomical fiducials at step1. Then I have tried "Apply" on Step 1. The "apply" registration in step1 seems to transform the moving image out of the field of view.  ( see attached image)
![image](https://user-images.githubusercontent.com/31940372/118412386-774a6280-b64e-11eb-80ee-ad964e4a291b.png)

Please advise for next steps. Thank you for your time.

**Comment by e-simpson** [comment]
Closing to track this issue in #8
